"""revision 4

Revision ID: 5be67895ab4d
Revises: cb6921b84bf1
Create Date: 2022-04-09 14:01:11.578570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5be67895ab4d'
down_revision = 'cb6921b84bf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people_migrations_with_multiple_pk', sa.Column('money', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people_migrations_with_multiple_pk', 'money')
    # ### end Alembic commands ###
