"""revision 3

Revision ID: cb6921b84bf1
Revises: d9d3205a5cf1
Create Date: 2022-04-09 14:00:23.462587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb6921b84bf1'
down_revision = 'd9d3205a5cf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people_migrations_with_multiple_pk',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('name', 'age')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('people_migrations_with_multiple_pk')
    # ### end Alembic commands ###
