"""revision 2

Revision ID: d9d3205a5cf1
Revises: 2f81577f200c
Create Date: 2022-04-09 13:41:26.003285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9d3205a5cf1'
down_revision = '2f81577f200c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people_migrations_with_pk',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('people_migrations_with_pk')
    # ### end Alembic commands ###
